{% set version = "0.13.1" %}

package:
  name: genanki
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/genanki/genanki-{{ version }}.tar.gz
  sha256: 84d090423a8879520465bfe9784083edacb8d35e2ba511fa5a1bdef01d8f71ed

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - cached-property
    - chevron
    - frozendict
    - pyyaml

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - genanki
  commands:
    - pip check

about:
  home: https://github.com/kerrickstaley/genanki
  summary: Generate Anki decks programmatically
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
