{% set version = "0.13.1" %}

package:
  name: genanki
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/g/genanki/genanki-{{ version }}.tar.gz
    sha256: 84d090423a8879520465bfe9784083edacb8d35e2ba511fa5a1bdef01d8f71ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - cached-property
    - chevron
    - frozendict
    - python >=3.6
    - pyyaml

test:
  imports:
    - genanki
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kerrickstaley/genanki
  summary: Generate Anki decks programmatically
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
